package com.astune.painter.api.imageProvider;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Global registry for {@link CanvasImageProvider} instances.
 * <p>
 * Unlike {@code CanvasRendererRegistry} which picks the first matching renderer,
 * this registry collects <em>all</em> providers whose {@code canProvide} returns true
 * — a single face may have multiple textures generated by different providers,
 * stored together in a {@link com.astune.painter.api.ResourcesBundle}.
 */
public class CanvasImageProviderRegistry {
    private static final List<Entry> PROVIDERS = new ArrayList<>();
    private static final CanvasImageProvider DEFAULT_PROVIDER = new DefaultCanvasImageProvider();

    private record Entry(CanvasImageProvider provider, int priority) {}

    static {
        // 默认提供者最低优先级，确保用户注册的提供者优先生成
        PROVIDERS.add(new Entry(DEFAULT_PROVIDER, Integer.MIN_VALUE));
    }

    /**
     * 注册自定义图像提供者。优先级越高越先生成纹理。
     */
    public static synchronized void register(CanvasImageProvider provider, int priority) {
        PROVIDERS.add(new Entry(provider, priority));
        PROVIDERS.sort(Comparator.comparingInt(Entry::priority).reversed()); // 降序
    }

    /**
     * 移除一个提供者。默认提供者不可移除。
     * @return true 表示移除成功
     */
    public static synchronized boolean unregister(CanvasImageProvider provider) {
        if (provider == DEFAULT_PROVIDER) return false;
        return PROVIDERS.removeIf(e -> e.provider == provider);
    }

    /**
     * 获取所有 {@code canProvide} 为 true 的提供者，按优先级降序排列。
     * 默认提供者始终包含在结果末尾。
     */
    public static List<CanvasImageProvider> resolveAll(ImageProviderContext context) {
        List<CanvasImageProvider> result = new ArrayList<>();
        for (Entry entry : PROVIDERS) {
            if (entry.provider.canProvide(context)) {
                result.add(entry.provider);
            }
        }
        return result;
    }
}
